"""
Project creation commands for AURORA-DEV CLI.
"""
from pathlib import Path
from typing import Optional
from uuid import uuid4

import typer
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn


console = Console()
app = typer.Typer(help="Create new AURORA-DEV projects")


PROJECT_TYPES = ["backend", "frontend", "fullstack", "api", "microservice", "cli", "library"]


@app.command(name="project")
def project(
    name: str = typer.Argument(..., help="Project name"),
    project_type: str = typer.Option(
        "fullstack",
        "--type", "-t",
        help="Project type",
        show_choices=True,
    ),
    tech_stack: Optional[str] = typer.Option(
        None,
        "--tech",
        help="Comma-separated technology stack (e.g., 'python,fastapi,postgresql')",
    ),
    output_dir: Optional[str] = typer.Option(
        None,
        "--output", "-o",
        help="Output directory (defaults to current directory)",
    ),
    description: Optional[str] = typer.Option(
        None,
        "--description", "-d",
        help="Project description",
    ),
    model: str = typer.Option(
        "claude-sonnet-4-20250514",
        "--model", "-m",
        help="Claude model to use",
    ),
    dry_run: bool = typer.Option(
        False,
        "--dry-run",
        help="Show what would be created without creating",
    ),
) -> None:
    """
    Create a new AURORA-DEV project.
    
    Examples:
        aurora create project my-api --type backend --tech python,fastapi
        aurora create project my-app --type fullstack --tech react,python,postgresql
    """
    if project_type not in PROJECT_TYPES:
        console.print(f"[red]✗ Invalid project type. Choose from: {', '.join(PROJECT_TYPES)}[/red]")
        raise typer.Exit(1)
    
    # Parse tech stack
    technologies = []
    if tech_stack:
        technologies = [t.strip() for t in tech_stack.split(",") if t.strip()]
    else:
        # Default tech stacks by type
        default_stacks = {
            "backend": ["python", "fastapi", "postgresql"],
            "frontend": ["typescript", "react", "tailwind"],
            "fullstack": ["python", "fastapi", "react", "postgresql"],
            "api": ["python", "fastapi", "redis"],
            "microservice": ["python", "fastapi", "redis", "docker"],
            "cli": ["python", "typer", "rich"],
            "library": ["python"],
        }
        technologies = default_stacks.get(project_type, ["python"])
    
    # Determine output path
    output_path = Path(output_dir) if output_dir else Path.cwd()
    project_path = output_path / name
    
    project_id = str(uuid4())
    
    if dry_run:
        console.print(Panel(
            f"[bold]Dry Run - Would create:[/bold]\n\n"
            f"  Project ID: {project_id[:8]}...\n"
            f"  Name: {name}\n"
            f"  Type: {project_type}\n"
            f"  Tech Stack: {', '.join(technologies)}\n"
            f"  Path: {project_path}\n"
            f"  Model: {model}",
            title="Project Preview",
            border_style="yellow",
        ))
        return
    
    console.print(f"\n[bold blue]Creating project:[/bold blue] {name}\n")
    
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
    ) as progress:
        # Step 1: Create directory
        task = progress.add_task("Creating project directory...", total=None)
        project_path.mkdir(parents=True, exist_ok=True)
        progress.update(task, description="[green]✓[/green] Created project directory")
        
        # Step 2: Generate config
        progress.update(task, description="Generating configuration...")
        config_content = f"""# AURORA-DEV Project Configuration
# Generated by AURORA-DEV CLI

project:
  id: "{project_id}"
  name: "{name}"
  type: "{project_type}"
  description: "{description or f'A {project_type} project created with AURORA-DEV'}"
  tech_stack:
{chr(10).join(f'    - {t}' for t in technologies)}

settings:
  model: "{model}"
  max_retries: 3
  enable_reflexion: true
  enable_memory: true

agents:
  maestro:
    enabled: true
    max_concurrent_tasks: 5
  architect:
    enabled: true
    design_depth: detailed
"""
        config_file = project_path / ".aurora.yaml"
        config_file.write_text(config_content)
        progress.update(task, description="[green]✓[/green] Generated configuration")
        
        # Step 3: Create basic structure
        progress.update(task, description="Creating project structure...")
        
        dirs_by_type = {
            "backend": ["src", "tests", "docs", "scripts"],
            "frontend": ["src", "public", "tests", "styles"],
            "fullstack": ["backend", "frontend", "shared", "docs", "tests"],
            "api": ["src", "tests", "docs"],
            "microservice": ["src", "tests", "docker", "k8s"],
            "cli": ["src", "tests", "docs"],
            "library": ["src", "tests", "docs", "examples"],
        }
        
        for dir_name in dirs_by_type.get(project_type, ["src"]):
            (project_path / dir_name).mkdir(exist_ok=True)
        
        # Create README
        readme_content = f"""# {name}

{description or f'A {project_type} project created with AURORA-DEV.'}

## Tech Stack

{chr(10).join(f'- {t}' for t in technologies)}

## Getting Started

This project was created with AURORA-DEV. Run the following to continue development:

```bash
cd {name}
aurora run
```

## Project ID

`{project_id}`
"""
        (project_path / "README.md").write_text(readme_content)
        progress.update(task, description="[green]✓[/green] Created project structure")
    
    console.print(Panel(
        f"[green]✓ Project created successfully![/green]\n\n"
        f"  [bold]Project ID:[/bold] {project_id[:8]}...\n"
        f"  [bold]Location:[/bold] {project_path}\n\n"
        f"  [dim]Next steps:[/dim]\n"
        f"    cd {name}\n"
        f"    aurora run",
        title=f"🎉 {name}",
        border_style="green",
    ))


@app.command(name="agent")
def agent(
    agent_type: str = typer.Argument(..., help="Agent type to create"),
    name: str = typer.Option(None, "--name", "-n", help="Custom agent name"),
) -> None:
    """
    Create a custom agent (advanced).
    
    This creates a custom agent definition for extending AURORA-DEV.
    """
    valid_types = [
        "research", "analyst", "developer", "tester", 
        "reviewer", "documenter", "deployer"
    ]
    
    if agent_type not in valid_types:
        console.print(f"[red]✗ Invalid agent type. Choose from: {', '.join(valid_types)}[/red]")
        raise typer.Exit(1)
    
    agent_name = name or f"custom_{agent_type}"
    
    console.print(f"[yellow]⚠ Custom agent creation not yet implemented[/yellow]")
    console.print(f"[dim]Would create: {agent_name} ({agent_type})[/dim]")
